set(SOURCE_FILE
	${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/player.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/player.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/objects/object_factory.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/objects/object_factory.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/structs/camera.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/structs/camera.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/spatial_partitioning/voxel_grid.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/world/spatial_partitioning/voxel_grid.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/game_state_manager.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/game_state_manager.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/context/render_context.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/context/player_context.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/context/player_context.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/context/render_context.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/playable_state.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/playable_state.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/setup_state.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/setup_state.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/abstract/game_state.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/game/state/abstract/game_state.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/common/file-ops.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/common/utils.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/common/utils.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/common/patterns/singleton.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/texture.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/texture.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/enum/block_data.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/objects/block_3_d.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/objects/block_3_d.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/utils/helper.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/utils/helper.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/utils/colors.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/utils/colors.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/structs/texture_region.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/structs/pos_tex_vertex.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/graphics/structs/pos_tex_vertex.cpp
)